### ISSUE TITLE
Code seems to not be implemented

### ISSUE THREAD

**Issue by jmcrey** [alexthebobo/pwp-capstones#1]
Unfortunately, it seems that the necessary classes have not been implemented for this project. Should you feel this is in error, please feel free to upload updated code to this repository. If uploaded, please comment on this issue that the code has been uploaded and I will proceed to review the updated code. When commenting on this issue, please mention my username using "@jmcrey" so I am notified of the change. If you have any questions or concerns, please do not hesitate to reach out.

**Comment by alexthebobo** [comment]
Hello,

@jmcrey ,I uploaded the right files now. I did both exercices, TomeRate and Murder.

Best

Alex

**Comment by alexthebobo** [comment]
Hello @jmcrey just wondering if you see the files now

Thx

Alex

**Comment by jmcrey** [comment]
@alexthebobo I apologize for the delay. I have reviewed the code for the TomeRater project. The code for MurderMystery appears to not have been uploaded. 

Please review the open issues and let me know if you have any questions.

Cheers,
Jeremiah
